  name: Run Tests                                                                                                                                                                                                  
  on: [push]                                                                                                                                                                                                       
  jobs:                                                                                                                                                                                                            
    tests:                                                                                                                                                                                                         
      runs-on: ubuntu-latest                                                                                                                                                                                       
      steps:      
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4                                                                                                                                                                              
          with:
            node-version: 18                                                                                                                                                                                       
        - run: npm ci
        - run: npx playwright install --with-deps chromium
        - run: xvfb-run npm run test:api
          continue-on-error: true
        - run: xvfb-run npm run test:web
          continue-on-error: true
